# Generated by Django 5.1.2 on 2024-10-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_application_last_application_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='last_application_date',
        ),
        migrations.RemoveField(
            model_name='application',
            name='rejection_reason',
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
    ]
